# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2763ad5c72c39e1ba629b3423987a0721f64f2341e2c2076fe251adae5272d6e72f8c8a6e1a52d283a56fc7e780a0c40e119d53f94ae0df6da4d479ddd3b70a

test:
  secret_key_base: 68224167b82e43f6fbe51cef1539b6535c87da4ad5395b827b996bd6c26ecceb94f974320162b626c77c247726d1a5034e9329d70b7f48707105f48d7c097fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
